"use client";
// import type { Metadata } from "next";
// i
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import "./globals.css";
import { ReactNode, useEffect } from "react";
import { Noto_Sans, Sour_Gummy } from "next/font/google";
import { Toaster } from "sonner";

import Navbar from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { initWallets } from "@/features/wallet/init";
import { useRestoreWallet } from "@/features/wallet/hooks/useRestoreWallet";
import { useSyncNetworkWithWallet } from "@/features/network/hooks/useSyncNetworkWithWallet";
import { useWalletOverview } from "@/features/wallet/hooks/useWalletOverview";
import { ThemeProvider } from "next-themes";
import { WalletOverviewDrawer } from "@/features/wallet/components/drawers/WalletOverviewDrawer";
import { WalletConnectDialog } from "@/features/wallet/components/modals/WalletConnectDialog";
import { NetworkSelectorManager } from "@/features/network/components/manager/NetworkSelectorManager";
import { useWalletBalanceSync } from "@/features/wallet/hooks/useWalletBalanceSync";

import { PushNotificationInitializer } from "@/features/push-notifications/PushNotificationInitializer";

const sourGummy = Sour_Gummy({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-logo",
  display: "swap",
});

const noto_sans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-noto",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  initWallets();
  useRestoreWallet();
  useWalletOverview();
  useWalletBalanceSync();
  useSyncNetworkWithWallet();

  return (
    <html
      lang="en"
      className={noto_sans.className}
      suppressContentEditableWarning
    >
      <body className="flex flex-col min-h-screen bg-background">
        {/* text-foreground  */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />

          <PushNotificationInitializer />
          <button className="border">Enviar notificación de prueba</button>
          <NetworkSelectorManager />
          <WalletConnectDialog />
          <WalletOverviewDrawer />
          <main className="flex-1 p-4">{children}</main>
          <Footer />
        </ThemeProvider>
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}
